// 蓝桥杯真题练习（C 语言版）——拖拽排序：把打乱的代码行按正确顺序排好
// lines 是打乱后的行，correct 记录正确顺序（lines[correct[i]] 是第 i 个正确行）
var lanqiaoExercises = [
 {
  "id": 0,
  "title": "蓝桥杯·数列求和(枚举)",
  "desc": "C 练习：求 1~100 中所有能被 3 或 5 整除的数的和",
  "lines": [
   "    }",
   "        if (i % 3 == 0 || i % 5 == 0) {",
   "        }",
   "    int sum = 0;",
   "#include <stdio.h>",
   "int main() {",
   "}",
   "    printf(\"%d\\n\", sum);",
   "            sum += i;",
   "    for (int i = 1; i <= 100; i++) {",
   "    return 0;"
  ],
  "correct": [
   4,
   5,
   3,
   9,
   1,
   8,
   2,
   0,
   7,
   10,
   6
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 1,
  "title": "蓝桥杯·字符统计(字符串)",
  "desc": "C 练习：统计字符串 hello blue bridge cup 中字母 l 出现的次数",
  "lines": [
   "#include <stdio.h>",
   "}",
   "    int count = 0;",
   "    printf(\"字母l出现: %d 次\\n\", count);",
   "    char s[] = \"hello blue bridge cup\";",
   "    }",
   "        if (s[i] == 'l') count++;",
   "    return 0;",
   "int main() {",
   "    for (int i = 0; s[i]; i++) {"
  ],
  "correct": [
   0,
   8,
   4,
   2,
   9,
   6,
   5,
   3,
   7,
   1
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 2,
  "title": "蓝桥杯·闰年判断(模拟)",
  "desc": "C 练习：输出 2000~2020 之间的所有闰年",
  "lines": [
   "            printf(\"%d\\n\", year);",
   "        int leap = (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;",
   "    }",
   "int main() {",
   "#include <stdio.h>",
   "}",
   "        }",
   "        if (leap) {",
   "    return 0;",
   "    for (int year = 2000; year <= 2020; year++) {"
  ],
  "correct": [
   4,
   3,
   9,
   1,
   7,
   0,
   6,
   2,
   8,
   5
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 3,
  "title": "蓝桥杯·最大公约数(数学)",
  "desc": "C 练习：用辗转相除法求 48 和 36 的最大公约数",
  "lines": [
   "int main() {",
   "    int a = 48, b = 36;",
   "    printf(\"最大公约数: %d\\n\", a);",
   "#include <stdio.h>",
   "        a = temp;",
   "}",
   "    }",
   "    while (b != 0) {",
   "        b = a % b;",
   "        int temp = b;",
   "    return 0;"
  ],
  "correct": [
   3,
   0,
   1,
   7,
   9,
   8,
   4,
   6,
   2,
   10,
   5
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 4,
  "title": "蓝桥杯·Fibonacci数列(递推)",
  "desc": "C 练习：输出斐波那契数列前 15 项（1 1 2 3 5 ...）",
  "lines": [
   "#include <stdio.h>",
   "        a = b;",
   "int main() {",
   "    printf(\"%ld %ld \", a, b);",
   "    for (int i = 3; i <= 15; i++) {",
   "        b = c;",
   "}",
   "    long a = 1, b = 1;",
   "    }",
   "    return 0;",
   "        long c = a + b;",
   "        printf(\"%ld \", c);"
  ],
  "correct": [
   0,
   2,
   7,
   3,
   4,
   10,
   11,
   1,
   5,
   8,
   9,
   6
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 5,
  "title": "蓝桥杯·字符串反转(字符串)",
  "desc": "C 练习：把字符串 bluebridge 反转输出",
  "lines": [
   "    char s[] = \"bluebridge\";",
   "    printf(\"\\n\");",
   "}",
   "        putchar(s[i]);",
   "#include <stdio.h>",
   "    for (int i = strlen(s) - 1; i >= 0; i--) {",
   "int main() {",
   "    return 0;",
   "#include <string.h>",
   "    }"
  ],
  "correct": [
   4,
   8,
   6,
   0,
   5,
   3,
   9,
   1,
   7,
   2
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 6,
  "title": "蓝桥杯·删除重复字符(数组)",
  "desc": "C 练习：去掉字符串 aabbccddeeff 中的重复字符，输出 abcdef",
  "lines": [
   "    char s[] = \"aabbccddeeff\";",
   "int main() {",
   "        }",
   "        if (!seen[(unsigned char)s[i]]) {",
   "}",
   "    int seen[256] = {0};",
   "            seen[(unsigned char)s[i]] = 1;",
   "            putchar(s[i]);",
   "    }",
   "    for (int i = 0; s[i]; i++) {",
   "    printf(\"\\n\");",
   "#include <stdio.h>",
   "    return 0;"
  ],
  "correct": [
   11,
   1,
   0,
   5,
   9,
   3,
   6,
   7,
   2,
   8,
   10,
   12,
   4
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 7,
  "title": "蓝桥杯·回文数判断(模拟)",
  "desc": "C 练习：判断 12321 是不是回文数（反转后相等）",
  "lines": [
   "        t /= 10;",
   "        printf(\"%d 不是回文数\\n\", num);",
   "    int num = 12321;",
   "    while (t > 0) {",
   "    return 0;",
   "    int rev = 0, t = num;",
   "#include <stdio.h>",
   "    if (rev == num) {",
   "}",
   "        rev = rev * 10 + t % 10;",
   "        printf(\"%d 是回文数\\n\", num);",
   "    }",
   "    } else {",
   "int main() {",
   "    }"
  ],
  "correct": [
   6,
   13,
   2,
   5,
   3,
   9,
   0,
   14,
   7,
   10,
   12,
   1,
   11,
   4,
   8
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 8,
  "title": "蓝桥杯·冒泡排序(排序)",
  "desc": "C 练习：用冒泡排序把 {9,5,7,3,1} 从小到大排序后输出",
  "lines": [
   "#include <stdio.h>",
   "        for (int j = 0; j < n - 1 - i; j++) {",
   "int main() {",
   "    int arr[] = {9, 5, 7, 3, 1};",
   "}",
   "    int n = 5;",
   "    }",
   "        }",
   "                arr[j + 1] = t;",
   "    for (int i = 0; i < n - 1; i++) {",
   "    return 0;",
   "    printf(\"\\n\");",
   "            if (arr[j] > arr[j + 1]) {",
   "                int t = arr[j];",
   "                arr[j] = arr[j + 1];",
   "            }",
   "    for (int i = 0; i < n; i++) printf(\"%d \", arr[i]);"
  ],
  "correct": [
   0,
   2,
   3,
   5,
   9,
   1,
   12,
   13,
   14,
   8,
   15,
   7,
   6,
   16,
   11,
   10,
   4
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 9,
  "title": "蓝桥杯·二分查找(查找)",
  "desc": "C 练习：在有序数组 {1,3,5,7,9,11,13} 中二分查找 7 的下标",
  "lines": [
   "}",
   "        } else {",
   "    int result = -1;",
   "        }",
   "            right = mid - 1;",
   "    printf(\"7的下标: %d\\n\", result);",
   "            break;",
   "        if (arr[mid] == target) {",
   "    int n = 7, target = 7;",
   "    while (left <= right) {",
   "            left = mid + 1;",
   "        int mid = (left + right) / 2;",
   "    return 0;",
   "    int left = 0, right = n - 1;",
   "    }",
   "int main() {",
   "        } else if (arr[mid] < target) {",
   "    int arr[] = {1, 3, 5, 7, 9, 11, 13};",
   "            result = mid;",
   "#include <stdio.h>"
  ],
  "correct": [
   19,
   15,
   17,
   8,
   13,
   2,
   9,
   11,
   7,
   18,
   6,
   16,
   10,
   1,
   4,
   3,
   14,
   5,
   12,
   0
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 10,
  "title": "蓝桥杯·杨辉三角(二维数组)",
  "desc": "C 练习：输出 6 行杨辉三角",
  "lines": [
   "    int n = 6;",
   "            tri[i][j] = tri[i - 1][j - 1] + tri[i - 1][j];",
   "    int tri[10][10] = {0};",
   "        }",
   "    }",
   "        tri[i][0] = 1;",
   "#include <stdio.h>",
   "        tri[i][i] = 1;",
   "        for (int j = 0; j <= i; j++) printf(\"%d \", tri[i][j]);",
   "    for (int i = 0; i < n; i++) {",
   "    }",
   "    for (int i = 0; i < n; i++) {",
   "}",
   "    return 0;",
   "int main() {",
   "        for (int j = 1; j < i; j++) {",
   "        printf(\"\\n\");"
  ],
  "correct": [
   6,
   14,
   0,
   2,
   11,
   5,
   7,
   15,
   1,
   3,
   4,
   9,
   8,
   16,
   10,
   13,
   12
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 11,
  "title": "蓝桥杯·数字三角形(动态规划)",
  "desc": "C 练习：从三角形顶端走到底部，求路径数字之和的最大值",
  "lines": [
   "    printf(\"最大路径和: %d\\n\", dp[0][0]);",
   "    for (int i = n - 2; i >= 0; i--) {",
   "    return 0;",
   "            dp[i][j] = m + t[i][j];",
   "    int t[4][4] = {{7}, {3, 8}, {8, 1, 0}, {2, 7, 4, 4}};",
   "    int n = 4;",
   "        }",
   "        for (int j = 0; j <= i; j++) {",
   "#include <stdio.h>",
   "    for (int j = 0; j < n; j++) dp[n - 1][j] = t[n - 1][j];",
   "    }",
   "}",
   "    int dp[4][4] = {0};",
   "int main() {",
   "            int m = dp[i + 1][j] > dp[i + 1][j + 1] ? dp[i + 1][j] : dp[i + 1][j + 1];"
  ],
  "correct": [
   8,
   13,
   4,
   12,
   5,
   9,
   1,
   7,
   14,
   3,
   6,
   10,
   0,
   2,
   11
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 12,
  "title": "蓝桥杯·01背包(动态规划)",
  "desc": "C 练习：容量 10 的背包，4 件物品（重量/价值），求最大价值",
  "lines": [
   "    for (int i = 0; i < n; i++) {",
   "    int v[] = {3, 4, 5, 6};",
   "    int n = 4;",
   "    printf(\"最大价值: %d\\n\", dp[cap]);",
   "    return 0;",
   "    int cap = 10;",
   "        for (int j = cap; j >= w[i]; j--) {",
   "            int x = dp[j - w[i]] + v[i];",
   "    int w[] = {2, 3, 4, 5};",
   "#include <stdio.h>",
   "        }",
   "}",
   "int main() {",
   "    int dp[11] = {0};",
   "            if (x > dp[j]) dp[j] = x;",
   "    }"
  ],
  "correct": [
   9,
   12,
   5,
   8,
   1,
   2,
   13,
   0,
   6,
   7,
   14,
   10,
   15,
   3,
   4,
   11
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 13,
  "title": "蓝桥杯·走迷宫BFS(图)",
  "desc": "C 练习：4×4 迷宫从 (0,0) 走到 (3,3)，0 可走 1 是墙，求最少步数",
  "lines": [
   "        }",
   "        int x = qx[head], y = qy[head], s = qs[head];",
   "int main() {",
   "    int ans = -1;",
   "        head++;",
   "int vis[4][4];",
   "    {1, 0, 1, 0},",
   "#include <stdio.h>",
   "int qx[100], qy[100], qs[100];",
   "    {0, 0, 0, 1},",
   "};",
   "                vis[nx][ny] = 1;",
   "            int nx = x + dx[k], ny = y + dy[k];",
   "    }",
   "            if (nx >= 0 && nx < 4 && ny >= 0 && ny < 4 && maze[nx][ny] == 0 && !vis[nx][ny]) {",
   "            }",
   "    qx[tail] = 0; qy[tail] = 0; qs[tail] = 0; tail++;",
   "    printf(\"最少步数: %d\\n\", ans);",
   "    vis[0][0] = 1;",
   "    while (head < tail) {",
   "    {0, 0, 0, 0}",
   "int maze[4][4] = {",
   "    int head = 0, tail = 0;",
   "    return 0;",
   "        if (x == 3 && y == 3) { ans = s; break; }",
   "    int dx[] = {0, 0, 1, -1}, dy[] = {1, -1, 0, 0};",
   "    {0, 1, 0, 0},",
   "        for (int k = 0; k < 4; k++) {",
   "}",
   "                qx[tail] = nx; qy[tail] = ny; qs[tail] = s + 1; tail++;"
  ],
  "correct": [
   7,
   21,
   26,
   9,
   6,
   20,
   10,
   5,
   8,
   2,
   25,
   22,
   16,
   18,
   3,
   19,
   1,
   4,
   24,
   27,
   12,
   14,
   11,
   29,
   15,
   0,
   13,
   17,
   23,
   28
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 },
 {
  "id": 14,
  "title": "蓝桥杯·最大子段和(DP)",
  "desc": "C 练习：求数组 {-2,11,-4,13,-5,-2} 中连续子数组的最大和",
  "lines": [
   "    printf(\"最大子段和: %d\\n\", best);",
   "        if (cur > best) best = cur;",
   "#include <stdio.h>",
   "    int nums[] = {-2, 11, -4, 13, -5, -2};",
   "    return 0;",
   "}",
   "int main() {",
   "        cur = nums[i] > cur + nums[i] ? nums[i] : cur + nums[i];",
   "    int n = 6;",
   "    int cur = nums[0], best = nums[0];",
   "    for (int i = 1; i < n; i++) {",
   "    }"
  ],
  "correct": [
   2,
   6,
   3,
   8,
   9,
   10,
   7,
   1,
   11,
   0,
   4,
   5
  ],
  "xp": 20,
  "difficulty": "挑战",
  "explain": {}
 }
];
